### ISSUE TITLE
Permissions error: No guild.

### ISSUE THREAD

**Issue by sohamdata** [openai/dallify-discord-bot#1]
With the bot set up successfully as instructed, it doesn't work. It shows `Error: You don't have permission to do that.` on discord when /draw is used.
![image](https://user-images.githubusercontent.com/78294692/201398712-06e1c387-26be-4b7d-862e-3d20ef0f7333.png)

on terminal, `Permissions error: No guild.` is thrown.
![image](https://user-images.githubusercontent.com/78294692/201398659-c3cc056c-a44f-4af7-b54d-45e8cba46bd8.png)

**Comment by YufeiG** [comment]
No guild means there's no server. Are you dming the bot? There is no dm support.
