### ISSUE TITLE
Permissions error: Guild ### not allowed

### ISSUE THREAD

**Issue by Rajackar** [openai/dallify-discord-bot#2]
Hi, I've gone over the instructions multiple times but I can't get the bot to work.
First time launching it I would get the "no guild" error but after a restart this went away.
I see the Bot in my server and set it up with appropriate permissions.
Whenever I try to use /draw "something" I get an error on Discord: "Error: You don't have permission to do that."
And the following error on the console output of node "Permissions error: Guild ############## not allowed." the ###### matches my server ID I got using the instructions provided.
I'm at a bit of a loss here.
Do you have any idea what might cause this or is there a way to turn on more verbose logging?
Thanks!

**Comment by Rajackar** [comment]
User error. Issue resolved.

**Comment by jomifepe** [comment]
> User error. Issue resolved.

How did you solve it?

**Comment by Rajackar** [comment]
I had incorrect ID

Op do 2 mrt 2023 om 10:48 schreef José Pereira ***@***.***>:
